### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by moreati** [moreati/ansible-uv#2]
`moreati.uv.pip` tries to use the Python module `packaging`. This doesn't exist by default, in a virtualenv created by `uv`.

```
TASK [Install paramiko] *******************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'packaging'
fatal: [slinger.internal]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (packaging) on slinger.internal's Python /home/slinger/.ansible_venv/bin/python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

**Comment by jamescooke** [comment]
Interested to hear what you think the solution is here. Maybe...

1. Install `packaging` if it's not already in place.
2. Adjust this repo to not require anything that `packaging` requires (maybe uv can provide 🙏🏻)
3. Something else? 🤔

**Comment by moreati** [comment]
> 2\. Adjust this repo to not require anything that `packaging` requires (maybe uv can provide 🙏🏻)

That's the goal, no plan or time scale yet. Best guess it may involve parsing the stdout of `uv`.

**Comment by moreati** [comment]
Grab bag of `uv` issues relating json/structured output

- https://github.com/astral-sh/uv/issues/411
- https://github.com/astral-sh/uv/issues/1442
- https://github.com/astral-sh/uv/issues/1566
- https://github.com/astral-sh/uv/issues/3199
- https://github.com/astral-sh/uv/issues/5279
